version: "3"
services:
   spark:
      build: .
      ports:
        - 10001:10001
      command: bash -c "SPARK_NO_DAEMONIZE=1 start-thriftserver.sh"
      volumes:
        - ./conf:/opt/spark/conf
        - ../hadoop/conf:/opt/hadoop/conf
      environment:
        - HADOOP_CONF_DIR=/opt/hadoop/conf

networks:
  default:
    name: bigdata
